import { createRemoteJWKSet, jwtVerify } from "jose";
import { APP_NAME, REPO_PREFIX } from "@/frontend/brand";

export const maxDuration = 60;

const JWKS = createRemoteJWKSet(
  new URL(
    "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
  )
);

async function verifyFirebaseToken(authHeader: string | null) {
  if (!authHeader?.startsWith("Bearer ")) return null;
  const token = authHeader.slice(7);
  const projectId = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
  if (!projectId) return null;
  try {
    const { payload } = await jwtVerify(token, JWKS, {
      issuer: `https://securetoken.google.com/${projectId}`,
      audience: projectId,
    });
    return payload.sub ?? null;
  } catch {
    return null;
  }
}

function slugify(name: string): string {
  const s = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return s || "app";
}

const GH = "https://api.github.com";

function ghHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "User-Agent": "asteriq-platform",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
}

function buildRepoFiles(opts: {
  name: string;
  code: string;
  login: string;
  repo: string;
}): { path: string; content: string }[] {
  const { name, code, login, repo } = opts;
  const liveUrl = `https://${login}.github.io/${repo}/`;
  const year = new Date().getFullYear();

  const readme = `# ${name}

Built with **${APP_NAME}** — India's AI no-code platform.

## 🌐 Live

${liveUrl}

## 📂 Project structure

| File | Purpose |
|------|---------|
| \`index.html\` | The complete application — HTML, CSS and JavaScript in one file |
| \`404.html\` | Fallback page so unknown URLs still load the app |
| \`asteriq.json\` | Project metadata generated by ${APP_NAME} |

## ✏️ Editing

This is a self-contained static app. Edit \`index.html\` directly, or open the
project in ${APP_NAME} AI and keep building by chatting.

## 🚀 Hosting

Deployed automatically to GitHub Pages. Every deployment from ${APP_NAME} AI
creates a new commit on \`main\`.

---
_Generated on ${new Date().toISOString().slice(0, 10)}_
`;

  const license = `MIT License

Copyright (c) ${year} ${login}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

  const gitignore = `.DS_Store
Thumbs.db
node_modules/
.env
.env.local
`;

  const manifest = JSON.stringify(
    {
      name,
      generator: `${APP_NAME} AI`,
      type: "static-app",
      live: liveUrl,
      repository: `https://github.com/${login}/${repo}`,
      deployedAt: new Date().toISOString(),
    },
    null,
    2
  );

  return [
    { path: "index.html", content: code },
    { path: "404.html", content: code },
    { path: "README.md", content: readme },
    { path: "LICENSE", content: license },
    { path: ".gitignore", content: gitignore },
    { path: "asteriq.json", content: manifest },
  ];
}

/** Push all files as ONE atomic commit using the Git Data API. */
async function pushAllFiles(
  token: string,
  login: string,
  repo: string,
  files: { path: string; content: string }[],
  message: string
): Promise<{ ok: boolean; error?: string }> {
  const H = ghHeaders(token);

  // 1. Current main ref (retry — fresh repos can lag)
  let refRes: Response | null = null;
  for (let i = 0; i < 3; i++) {
    refRes = await fetch(`${GH}/repos/${login}/${repo}/git/ref/heads/main`, {
      headers: H,
    });
    if (refRes.ok) break;
    await new Promise((r) => setTimeout(r, 2000));
  }
  if (!refRes || !refRes.ok) {
    return { ok: false, error: "Could not read the repository's main branch." };
  }
  const baseSha = (await refRes.json()).object.sha as string;

  const commitRes = await fetch(
    `${GH}/repos/${login}/${repo}/git/commits/${baseSha}`,
    { headers: H }
  );
  if (!commitRes.ok) return { ok: false, error: "Could not read base commit." };
  const baseTree = (await commitRes.json()).tree.sha as string;

  // 2. New tree with every file
  const treeRes = await fetch(`${GH}/repos/${login}/${repo}/git/trees`, {
    method: "POST",
    headers: H,
    body: JSON.stringify({
      base_tree: baseTree,
      tree: files.map((f) => ({
        path: f.path,
        mode: "100644",
        type: "blob",
        content: f.content,
      })),
    }),
  });
  if (!treeRes.ok) {
    const e = await treeRes.json().catch(() => ({}));
    return { ok: false, error: `Could not create file tree: ${e.message || treeRes.status}` };
  }
  const newTree = (await treeRes.json()).sha as string;

  // 3. Commit
  const newCommitRes = await fetch(`${GH}/repos/${login}/${repo}/git/commits`, {
    method: "POST",
    headers: H,
    body: JSON.stringify({ message, tree: newTree, parents: [baseSha] }),
  });
  if (!newCommitRes.ok) return { ok: false, error: "Could not create commit." };
  const newCommit = (await newCommitRes.json()).sha as string;

  // 4. Move main to the new commit
  const updateRes = await fetch(
    `${GH}/repos/${login}/${repo}/git/refs/heads/main`,
    {
      method: "PATCH",
      headers: H,
      body: JSON.stringify({ sha: newCommit }),
    }
  );
  if (!updateRes.ok) return { ok: false, error: "Could not update main branch." };

  return { ok: true };
}

export async function POST(req: Request) {
  const uid = await verifyFirebaseToken(req.headers.get("authorization"));
  if (!uid) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { name, code, githubToken, existingRepo } = (await req.json()) as {
    name: string;
    code: string;
    githubToken?: string;
    /** Repo name from a previous deploy — reuse it, never create a duplicate */
    existingRepo?: string;
  };
  if (!name || !code) {
    return Response.json({ error: "Missing name or code" }, { status: 400 });
  }

  const token = githubToken;
  if (!token) {
    return Response.json(
      {
        error:
          "Connect your GitHub account first — go to Connections and click Connect GitHub.",
      },
      { status: 400 }
    );
  }

  try {
    // Who is deploying?
    const userRes = await fetch(`${GH}/user`, { headers: ghHeaders(token) });
    if (!userRes.ok) {
      return Response.json(
        {
          error:
            "Your GitHub token is invalid or expired. Go to Connections and reconnect GitHub.",
        },
        { status: 400 }
      );
    }
    const { login } = await userRes.json();

    // Reuse the project's existing repo when it has one — deploys UPDATE, never duplicate.
    const repo =
      existingRepo && /^[A-Za-z0-9._-]+$/.test(existingRepo)
        ? existingRepo
        : `${REPO_PREFIX}-${slugify(name)}`;

    // Create repo if it doesn't exist
    const repoRes = await fetch(`${GH}/repos/${login}/${repo}`, {
      headers: ghHeaders(token),
    });
    if (repoRes.status === 404) {
      const createRes = await fetch(`${GH}/user/repos`, {
        method: "POST",
        headers: ghHeaders(token),
        body: JSON.stringify({
          name: repo,
          description: `Built with ${APP_NAME} AI — ${name}`,
          auto_init: true,
          has_issues: false,
          has_wiki: false,
        }),
      });
      if (!createRes.ok) {
        const err = await createRes.json().catch(() => ({}));
        return Response.json(
          { error: `Could not create repository: ${err.message || createRes.status}` },
          { status: 500 }
        );
      }
      await new Promise((r) => setTimeout(r, 2000));
    }

    // Push the complete project in one commit
    const files = buildRepoFiles({ name, code, login, repo });
    const push = await pushAllFiles(
      token,
      login,
      repo,
      files,
      `Deploy from ${APP_NAME} AI — ${new Date().toLocaleString("en-IN")}`
    );
    if (!push.ok) {
      return Response.json({ error: push.error }, { status: 500 });
    }

    // Enable GitHub Pages (409 = already enabled)
    await fetch(`${GH}/repos/${login}/${repo}/pages`, {
      method: "POST",
      headers: ghHeaders(token),
      body: JSON.stringify({ source: { branch: "main", path: "/" } }),
    }).catch(() => null);

    return Response.json({
      repoUrl: `https://github.com/${login}/${repo}`,
      pagesUrl: `https://${login}.github.io/${repo}/`,
      repoName: repo,
      filesPushed: files.map((f) => f.path),
    });
  } catch (err) {
    console.error(err);
    return Response.json(
      { error: "Deployment failed. Check your connection and try again." },
      { status: 500 }
    );
  }
}
